version: '3'

services:
  authorization-server:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
      - 9227:9229
    command: npm run dev
