version: '3'

services:
  protected-resource:
    build: .
    volumes:
      - ./dist:/usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
      - 9227:9229
    command: npm run map-debug
